### ISSUE TITLE
Support for Swagger 2.0

### ISSUE THREAD

**Issue by josephpconley** [josephpconley/swagger2postman#3]
While Postman supports importing a Swagger collection, the functionality does not group Swagger paths into folders (which would be an intuitive thing to do) so there is still a need to support Swagger 2.0 here

**Comment by arielcloud** [comment]
someone can help me? - if i use swagger ui in my asp.net core app, can i get this work on postman? so that i can see in postman all my rest api?
any tutorial? thanks!

**Comment by josephpconley** [comment]
Hi, what version of Swagger are you working with?  If you're working with 1.2, you can go to http://app.josephpconley.com/swagger2postman and generate a JSON file that can be imported into Postman so you can see your entire REST API.

I'm still wrapping up work for Swagger 2.0 support.  I'm hoping to have it done by next week, at which point you can follow that same link and the app will be updated for Swagger 2.0.

**Comment by arielcloud** [comment]
I'm using Swashbuckle 6 that use swagger 2.0.
You expect in the future any possibility to dynamically link postman and swagger, so you can get swagger ui automatically on postman after each build, without generating new json every time? 10x!

**Comment by josephpconley** [comment]
I'd have to look into a Postman integration that allows for uploading
collections automatically, but what you're describing would require
generating new json every time the API info from swagger changes.

**Comment by rjack2** [comment]
Joseph,

This seems to be just the tool, I"m looking for. I will need the Swagger 2.0 version also.

Regards,

**Comment by josephpconley** [comment]
Please take a look at the latest README for instructions on how to use the Swagger 2.0 functionality.  Thanks!
